
import javafx.stage.Screen;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows.10
 */
public class interface1 extends javax.swing.JFrame {

    /**
     * Creates new form interface1
     */
    
    
    Graph g;
    int v;
    int s;
    int d;
    int w;
    int e;
    int num_of_edge;
    
    public interface1() {
        initComponents();
        this.g= new Graph(v);
        add_edge.setEnabled(false);
        create_graph.setEnabled(true);
        print_graph.setEnabled(false);
        clear.setEnabled(true);
        Run_dijkstra.setEnabled(false);
        Run_bellmanford.setEnabled(false);
        create_random_graph.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        create_graph = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        add_edge = new javax.swing.JButton();
        print_graph = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Run_dijkstra = new javax.swing.JButton();
        Run_bellmanford = new javax.swing.JButton();
        create_random_graph = new javax.swing.JButton();
        run_thired_algorithem = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("weight");

        jLabel4.setText("distination");

        jLabel5.setText("source");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("num vertex");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel2.setText("num edge");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        create_graph.setText("create Graph");
        create_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_graphActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        add_edge.setText("add edge");
        add_edge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_edgeActionPerformed(evt);
            }
        });

        print_graph.setText("Print Graph");
        print_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_graphActionPerformed(evt);
            }
        });

        clear.setLabel("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Run_dijkstra.setText("run dijkstra");
        Run_dijkstra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run_dijkstraActionPerformed(evt);
            }
        });

        Run_bellmanford.setText("run bellman ford");
        Run_bellmanford.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Run_bellmanfordActionPerformed(evt);
            }
        });

        create_random_graph.setText("create random graph");
        create_random_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_random_graphActionPerformed(evt);
            }
        });

        run_thired_algorithem.setText("run thired algorithem");
        run_thired_algorithem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                run_thired_algorithem(evt);
            }
        });

        jLabel7.setText("Enter source");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Run_bellmanford, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Run_dijkstra, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(run_thired_algorithem))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(create_graph))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(create_random_graph))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(print_graph, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(add_edge, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_edge))
                        .addGap(38, 38, 38)
                        .addComponent(clear)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(create_graph))
                        .addGap(46, 46, 46)
                        .addComponent(create_random_graph)
                        .addGap(18, 18, 18)
                        .addComponent(print_graph)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Run_dijkstra)
                        .addGap(18, 18, 18)
                        .addComponent(Run_bellmanford)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(run_thired_algorithem)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        add_edge.setEnabled(false);
        create_graph.setEnabled(true);
        print_graph.setEnabled(false);
        clear.setEnabled(true);
        Run_dijkstra.setEnabled(false);
        Run_bellmanford.setEnabled(false);
        create_random_graph.setEnabled(true);

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextArea1.setText("");

    }//GEN-LAST:event_clearActionPerformed

    private void add_edgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_edgeActionPerformed
        
       if(jTextField3.getText().isEmpty()||jTextField4.getText().isEmpty()||jTextField5.getText().isEmpty())
    JOptionPane.showMessageDialog(null, "Please Enter an edge!",
      "Error!", JOptionPane.ERROR_MESSAGE);
       else
       {
        s=Integer.parseInt(jTextField3.getText());
        d=Integer.parseInt(jTextField4.getText());
        w=Integer.parseInt(jTextField5.getText());
        
        
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        create_graph.setEnabled(true);
        
           g.add_edge(s,d,w);
       }
        
    }//GEN-LAST:event_add_edgeActionPerformed

    private void create_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_graphActionPerformed
        v=Integer.parseInt(jTextField1.getText());
        g=new Graph(v);
        print_graph.setEnabled(true);
        add_edge.setEnabled(true);
    }//GEN-LAST:event_create_graphActionPerformed

    private void print_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_graphActionPerformed
        jTextArea1.setText("printing the input graph \n");
        for (int   x=0;x<v;x++) 
            for(int j=0;j<v;j++)
                if(g.graph[x][j]!=0)
                jTextArea1.append( "the edge ( "+x+","+j+") has weight :"+"\t"+g.graph[x][j] + "\n");   
            
      
        Run_dijkstra.setEnabled(true);
        Run_bellmanford.setEnabled(true);
        
        
    }//GEN-LAST:event_print_graphActionPerformed
    
    private void Run_dijkstraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run_dijkstraActionPerformed
if(jTextField6.getText().isEmpty())
    JOptionPane.showMessageDialog(null, "Please Enter source!",
      "Error!", JOptionPane.ERROR_MESSAGE);
else{    
        s=Integer.parseInt(jTextField6.getText());
        long start = System.currentTimeMillis();
        
        g.dijkstra(s);
       
        long end = System.currentTimeMillis();
        long elapsedTime = end -start;
         String output="Dijkstra \n";
        for(int y=0;y<v;y++){
            output+="vertex "+y+" has distance "+g.getdist(y)+"\n";
         jTextArea1.setText(output);
        }
       
        jTextArea1.append("elapsedTime= " + elapsedTime);
}   
    }//GEN-LAST:event_Run_dijkstraActionPerformed

    private void Run_bellmanfordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Run_bellmanfordActionPerformed
if(jTextField6.getText().isEmpty())
    JOptionPane.showMessageDialog(null, "Please Enter source!",
      "Error!", JOptionPane.ERROR_MESSAGE);
else{      
         s=Integer.parseInt(jTextField6.getText());       
        long start = System.currentTimeMillis();
      
        g.BellmanFord(s);
        
        
        long end = System.currentTimeMillis();
        long elapsedTime = end -start;
         String output="Bellman \n";
        for(int y=0;y<v;y++){
            output+="vertex "+y+" has distance "+g.getdist(y)+"\n";
         jTextArea1.setText(output);
        }
       
        jTextArea1.append("elapsedTime= " + elapsedTime);
}
    }//GEN-LAST:event_Run_bellmanfordActionPerformed

    private void create_random_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_random_graphActionPerformed
 int m=Integer.parseInt(jTextField2.getText());
   g.directed_grapgh(m);
        
    }//GEN-LAST:event_create_random_graphActionPerformed

    private void run_thired_algorithem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_run_thired_algorithem

if(jTextField6.getText().isEmpty())
    JOptionPane.showMessageDialog(null, "Please Enter source!",
      "Error!", JOptionPane.ERROR_MESSAGE);
else{        
        s=Integer.parseInt(jTextField6.getText());
        long start = System.currentTimeMillis();
     
        g.shortestPath(s);
        jTextArea1.setText("Following are shortest distances" +"from source " + s );
       
        long end = System.currentTimeMillis();
        long elapsedTime = end -start;
         String output="Third Algorithm \n";
        for(int y=0;y<v;y++){
            output+="vertex "+y+" has distance "+g.getdist(y)+"\n";
         jTextArea1.setText(output);
        }
        jTextArea1.append("elapsedTime= " + elapsedTime);
}
    }//GEN-LAST:event_run_thired_algorithem
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interface1().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Run_bellmanford;
    private javax.swing.JButton Run_dijkstra;
    private javax.swing.JButton add_edge;
    private javax.swing.JButton clear;
    private javax.swing.JButton create_graph;
    private javax.swing.JButton create_random_graph;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton print_graph;
    private javax.swing.JButton run_thired_algorithem;
    // End of variables declaration//GEN-END:variables
}
